-- AlterTable
ALTER TABLE "PlatformSettings" ADD COLUMN     "allowGuestCheckout" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowVideoUploads" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "autoApproveProducts" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoApproveReviews" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoApproveVendors" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'TRY',
ADD COLUMN     "darkModeDefault" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "facebookPixelId" TEXT,
ADD COLUMN     "faviconUrl" TEXT,
ADD COLUMN     "freeShippingThreshold" DOUBLE PRECISION,
ADD COLUMN     "googleTagManagerId" TEXT,
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "lowStockThreshold" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "maintenanceMessage" TEXT NOT NULL DEFAULT 'We''ll be back shortly. Thanks for your patience!',
ADD COLUMN     "maxImagesPerProduct" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "maxLoginAttempts" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "maxProductPrice" DOUBLE PRECISION,
ADD COLUMN     "maxProductsPerVendor" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxReviewLength" INTEGER NOT NULL DEFAULT 2000,
ADD COLUMN     "metaDescription" TEXT NOT NULL DEFAULT 'Buy official merch from your favourite artists and creators.',
ADD COLUMN     "metaTitle" TEXT NOT NULL DEFAULT 'MerchStage — Your Merch, Your Stage',
ADD COLUMN     "minPayoutAmount" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ADD COLUMN     "minProductPrice" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "notifyAdminOnVendorApply" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyVendorOnSale" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "orderNotificationEmail" TEXT,
ADD COLUMN     "payoutSchedule" TEXT NOT NULL DEFAULT 'MANUAL',
ADD COLUMN     "platformTagline" TEXT NOT NULL DEFAULT 'Your merch, your stage.',
ADD COLUMN     "primaryColor" TEXT NOT NULL DEFAULT '#7C3AED',
ADD COLUMN     "requireEmailVerification" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "sessionDurationHours" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN     "supportPhone" TEXT,
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
